/**
 * gradesMock
 * ----------
 * Provides seed and mock data for the teacher dashboard g ra de s feature.
 */
import { seedSubjects2 } from "@/dashboard/teacher/components/assignments";
import { buildPublishedItems } from "./publishedAdapters";
import type { TeacherClassRosterStudent, TeacherGradeItem, TeacherGradeSubmission } from "./gradesTypes";

export { seedSubjects2 };

export const SUBJECT_CLASS_MAP: Record<string, string[]> = {
  Mathematics: ["S3A", "S3B"],
  Biology: ["S2A", "S2B"],
  Chemistry: ["S2A"],
  Physics: ["S2B", "S3A"],
  English: ["S1A", "S1B"],
  Geography: ["S1A", "S3A"],
};

export const seedGradeItems: TeacherGradeItem[] = [
  {
    id: "grade-item-001",
    title: "Linear Equations Homework",
    type: "assignment",
    maxScore: 20,
    subjectId: "subject-2-math",
    classLabel: "S3A",
    createdAt: "2026-02-20T09:00:00.000Z",
  },
  {
    id: "grade-item-002",
    title: "Algebra Mid Quiz",
    type: "quiz",
    maxScore: 15,
    subjectId: "subject-2-math",
    classLabel: "S3B",
    createdAt: "2026-02-24T10:30:00.000Z",
  },
  {
    id: "grade-item-003",
    title: "Cell Structure Exam",
    type: "exam",
    maxScore: 100,
    subjectId: "subject-2-bio",
    classLabel: "S2A",
    createdAt: "2026-02-18T08:15:00.000Z",
  },
  {
    id: "grade-item-004",
    title: "Elements and Compounds Quiz",
    type: "quiz",
    maxScore: 10,
    subjectId: "subject-2-chem",
    classLabel: "S2A",
    createdAt: "2026-02-22T07:45:00.000Z",
  },
  {
    id: "grade-item-005",
    title: "Newton Laws Final Exam",
    type: "exam",
    maxScore: 100,
    subjectId: "subject-2-physics",
    classLabel: "S3A",
    createdAt: "2026-03-04T11:10:00.000Z",
  },
  {
    id: "grade-item-006",
    title: "Poetry Reflection",
    type: "assignment",
    maxScore: 25,
    subjectId: "subject-2-english",
    classLabel: "S1A",
    createdAt: "2026-02-28T13:10:00.000Z",
  },
  {
    id: "grade-item-007",
    title: "Climate Zones Quiz",
    type: "quiz",
    maxScore: 20,
    subjectId: "subject-2-geography",
    classLabel: "S3A",
    createdAt: "2026-03-01T09:40:00.000Z",
  },
];

export const seedPublishedItems = buildPublishedItems();

export const seedClassRosterByClass: Record<string, TeacherClassRosterStudent[]> = {
  S2B: [
    { studentId: "student-physics-1", studentName: "Grace Kamikazi", className: "S2B" },
    { studentId: "student-physics-2", studentName: "Kevin Uwimana", className: "S2B" },
    { studentId: "student-physics-3", studentName: "Alice Uwimana", className: "S2B" },
    { studentId: "student-physics-4", studentName: "Jean Claude Nshimiyimana", className: "S2B" },
    { studentId: "student-physics-5", studentName: "Aline Mukamana", className: "S2B" },
  ],
  S3A: [
    { studentId: "student-001", studentName: "Ariana Cruz", className: "S3A" },
    { studentId: "student-002", studentName: "Miguel Santos", className: "S3A" },
    { studentId: "student-004", studentName: "Lara Mendoza", className: "S3A" },
    { studentId: "student-006", studentName: "Cedric Mugenzi", className: "S3A" },
  ],
  S3B: [
    { studentId: "student-101", studentName: "Clarisse Uwera", className: "S3B" },
    { studentId: "student-102", studentName: "Patrick Muhire", className: "S3B" },
  ],
  S2A: [
    { studentId: "student-003", studentName: "Bea Torres", className: "S2A" },
    { studentId: "student-201", studentName: "Giselle Iradukunda", className: "S2A" },
  ],
  S1A: [
    { studentId: "student-005", studentName: "Noah Ramos", className: "S1A" },
    { studentId: "student-301", studentName: "Daniel Ndayisenga", className: "S1A" },
  ],
};

export const seedGradeSubmissions: TeacherGradeSubmission[] = [
  {
    id: "submission-001",
    itemId: "q2-001",
    type: "quiz",
    subjectId: "subject-2-math",
    subjectName: "Mathematics",
    className: "S3A",
    studentId: "student-001",
    studentName: "Ariana Cruz",
    title: "Algebra Mid Quiz",
    assessmentTitle: "Algebra Mid Quiz",
    submittedAt: "2026-03-03T09:10:00.000Z",
    status: "submitted",
    score: null,
    maxScore: 20,
    submissionDetails: {
      questions: [
        {
          id: "math-q1",
          prompt: "Solve x + 4 = 10",
          studentAnswer: "x = 6",
          correctAnswer: "x = 6",
          points: 10,
          earnedPoints: 0,
        },
        {
          id: "math-q2",
          prompt: "Factor x^2 + 5x + 6",
          studentAnswer: "(x + 2)(x + 3)",
          correctAnswer: "(x + 2)(x + 3)",
          points: 10,
          earnedPoints: 0,
        },
      ],
    },
    quizAnswers: [
      { question: "Solve x + 4 = 10", selectedAnswer: "x = 6" },
      { question: "Factor x^2 + 5x + 6", selectedAnswer: "(x + 2)(x + 3)" },
    ],
  },
  {
    id: "submission-002",
    itemId: "a2-001",
    type: "assignment",
    subjectId: "subject-2-math",
    subjectName: "Mathematics",
    className: "S3A",
    studentId: "student-002",
    studentName: "Miguel Santos",
    title: "Linear Equations Homework",
    assessmentTitle: "Linear Equations Homework",
    submittedAt: "2026-03-02T12:30:00.000Z",
    status: "graded",
    score: 18,
    maxScore: 20,
    submissionDetails: {
      attachments: [
        { name: "linear-equations.pdf", url: "#" },
        { name: "workings.jpg", url: "#" },
      ],
      responseText:
        "I solved each equation step by step and checked by substituting values back into the original equation.",
    },
    assignmentAttachments: [
      { id: "attach-001", fileName: "linear-equations.pdf" },
      { id: "attach-002", fileName: "workings.jpg" },
    ],
    assignmentTextResponse:
      "I solved each equation step by step and checked by substituting values back into the original equation.",
  },
  {
    id: "submission-003",
    itemId: "e2-003",
    type: "exam",
    subjectId: "subject-2-bio",
    subjectName: "Biology",
    className: "S2A",
    studentId: "student-003",
    studentName: "Bea Torres",
    title: "Cell Structure Exam",
    assessmentTitle: "Cell Structure Exam",
    submittedAt: "2026-03-01T08:40:00.000Z",
    status: "submitted",
    score: null,
    maxScore: 100,
    submissionDetails: {
      questions: [
        {
          id: "bio-q1",
          prompt: "Name the function of the nucleus.",
          studentAnswer: "It controls cell activities and stores DNA.",
          correctAnswer: "Control center containing genetic material.",
          points: 20,
          earnedPoints: 0,
        },
        {
          id: "bio-q2",
          prompt: "Identify two organelles involved in protein synthesis.",
          studentAnswer: "Ribosomes and rough ER.",
          correctAnswer: "Ribosomes and rough endoplasmic reticulum.",
          points: 20,
          earnedPoints: 0,
        },
      ],
    },
  },
  {
    id: "submission-004",
    itemId: "q2-006",
    type: "quiz",
    subjectId: "subject-2-geography",
    subjectName: "Geography",
    className: "S3A",
    studentId: "student-004",
    studentName: "Lara Mendoza",
    title: "Climate Zones Quiz",
    assessmentTitle: "Climate Zones Quiz",
    submittedAt: "2026-03-04T07:50:00.000Z",
    status: "graded",
    score: 16,
    maxScore: 20,
  },
  {
    id: "submission-005",
    itemId: "a2-005",
    type: "assignment",
    subjectId: "subject-2-english",
    subjectName: "English",
    className: "S1A",
    studentId: "student-005",
    studentName: "Noah Ramos",
    title: "Poetry Reflection",
    assessmentTitle: "Poetry Reflection",
    submittedAt: "2026-03-03T14:25:00.000Z",
    status: "submitted",
    score: null,
    maxScore: 25,
    submissionDetails: {
      attachments: [{ name: "poetry-reflection.docx", url: "#" }],
      responseText:
        "The poem uses imagery to express grief, and the shifting rhythm mirrors the speaker's emotional instability.",
    },
    assignmentAttachments: [{ id: "attach-003", fileName: "poetry-reflection.docx" }],
    assignmentTextResponse:
      "The poem uses imagery to express grief, and the shifting rhythm mirrors the speaker's emotional instability.",
  },
  {
    id: "sub-physics-1",
    itemId: "e2-004",
    type: "exam",
    subjectId: "subject-2-physics",
    subjectName: "Physics",
    className: "S2B",
    studentId: "student-physics-1",
    studentName: "Grace Kamikazi",
    title: "Newton Laws Final Exam",
    assessmentTitle: "Newton Laws Final Exam",
    submittedAt: "2026-03-05T10:15:00.000Z",
    status: "graded",
    score: 75,
    maxScore: 100,
    submissionDetails: {
      questions: [
        {
          id: "phy-q1",
          prompt: "State Newton's First Law.",
          studentAnswer: "An object in motion stays in motion unless acted on by an external force.",
          correctAnswer: "An object remains at rest or in uniform motion unless acted on by a net force.",
          points: 20,
          earnedPoints: 16,
        },
        {
          id: "phy-q2",
          prompt: "Calculate acceleration for force 20 N and mass 4 kg.",
          studentAnswer: "4 m/s^2",
          correctAnswer: "5 m/s^2",
          points: 20,
          earnedPoints: 12,
        },
        {
          id: "phy-q3",
          prompt: "Give one example of Newton's Third Law.",
          studentAnswer: "Rocket thrust and gas push.",
          correctAnswer: "Any valid action-reaction pair.",
          points: 20,
          earnedPoints: 15,
        },
        {
          id: "phy-q4",
          prompt: "Define net force.",
          studentAnswer: "The sum of all forces on an object.",
          correctAnswer: "The vector sum of all forces acting on an object.",
          points: 20,
          earnedPoints: 16,
        },
        {
          id: "phy-q5",
          prompt: "Why do seatbelts reduce injury?",
          studentAnswer: "They reduce inertia.",
          correctAnswer: "They increase stopping time which lowers force.",
          points: 20,
          earnedPoints: 16,
        },
      ],
    },
  },
  {
    id: "sub-physics-2",
    itemId: "e2-004",
    type: "exam",
    subjectId: "subject-2-physics",
    subjectName: "Physics",
    className: "S2B",
    studentId: "student-physics-2",
    studentName: "Kevin Uwimana",
    title: "Newton Laws Final Exam",
    assessmentTitle: "Newton Laws Final Exam",
    submittedAt: "2026-03-05T10:18:00.000Z",
    status: "submitted",
    score: null,
    maxScore: 100,
    submissionDetails: {
      questions: [
        {
          id: "phy2-q1",
          prompt: "State Newton's First Law.",
          studentAnswer: "Objects keep doing what they are doing without force.",
          correctAnswer: "Inertia statement with balanced forces.",
          points: 20,
          earnedPoints: 0,
        },
        {
          id: "phy2-q2",
          prompt: "Calculate acceleration for force 30 N and mass 6 kg.",
          studentAnswer: "5 m/s^2",
          correctAnswer: "5 m/s^2",
          points: 20,
          earnedPoints: 0,
        },
        {
          id: "phy2-q3",
          prompt: "Give an example of Newton's Third Law.",
          studentAnswer: "Walking.",
          correctAnswer: "Foot pushes ground, ground pushes foot.",
          points: 20,
          earnedPoints: 0,
        },
        {
          id: "phy2-q4",
          prompt: "Define momentum.",
          studentAnswer: "Mass times velocity.",
          correctAnswer: "Momentum p equals m times v.",
          points: 20,
          earnedPoints: 0,
        },
        {
          id: "phy2-q5",
          prompt: "Why do helmets reduce injuries?",
          studentAnswer: "Less force on the head.",
          correctAnswer: "They increase impact duration to reduce force.",
          points: 20,
          earnedPoints: 0,
        },
      ],
    },
  },
  {
    id: "sub-physics-3",
    itemId: "e2-004",
    type: "exam",
    subjectId: "subject-2-physics",
    subjectName: "Physics",
    className: "S2B",
    studentId: "student-physics-3",
    studentName: "Alice Uwimana",
    title: "Energy and Motion Exam",
    assessmentTitle: "Energy & Motion Exam",
    submittedAt: "2026-03-06T09:30:00.000Z",
    status: "graded",
    score: 68,
    maxScore: 100,
    submissionDetails: {
      questions: [
        {
          id: "phy3-q1",
          prompt: "Define kinetic energy.",
          studentAnswer: "Energy of movement.",
          correctAnswer: "KE = 1/2mv^2.",
          points: 20,
          earnedPoints: 14,
        },
        {
          id: "phy3-q2",
          prompt: "State the potential energy formula.",
          studentAnswer: "mgh",
          correctAnswer: "PE = mgh.",
          points: 20,
          earnedPoints: 16,
        },
        {
          id: "phy3-q3",
          prompt: "State conservation of energy.",
          studentAnswer: "Energy cannot be created or destroyed.",
          correctAnswer: "Same statement.",
          points: 20,
          earnedPoints: 15,
        },
        {
          id: "phy3-q4",
          prompt: "Convert 20 m/s to km/h.",
          studentAnswer: "72 km/h",
          correctAnswer: "72 km/h",
          points: 20,
          earnedPoints: 20,
        },
        {
          id: "phy3-q5",
          prompt: "Write the work formula.",
          studentAnswer: "Force times distance.",
          correctAnswer: "W = Fd.",
          points: 20,
          earnedPoints: 3,
        },
      ],
    },
  },
];

export const gradeSubmissionsMock: TeacherGradeSubmission[] = seedGradeSubmissions;

