// Provides the second half of seeded subject modules for physics.
import type { SubjectModuleItem } from "./subjectModulesTypes";

export const subjectModulesSeedPhysicsB: SubjectModuleItem[] = [
  {
    id: "waves-and-sound",
    title: "Waves and Sound",
    description: "Understand wave properties, sound transmission, frequency, and amplitude.",
    status: "draft",
    lessons: 3,
    duration: "1 week",
    order: 2,
    attachedFileIds: [],
    submodules: [
      {
        id: "properties-of-waves",
        title: "Properties of Waves",
        description: "Review wavelength, amplitude, frequency, and wave speed.",
        content: "A structured lesson with labeled diagrams, practice vocabulary, and quick wave-comparison tasks for class discussion.",
        attachedFileIds: [],
        summary: "A structured lesson with labeled diagrams, practice vocabulary, and quick wave-comparison tasks for class discussion.",
        order: 0,
      },
      {
        id: "sound-propagation",
        title: "Sound Propagation",
        description: "Trace how sound travels through solids, liquids, and gases.",
        content: "Students explore particle vibration, transfer media, and why sound behaves differently across materials.",
        attachedFileIds: [],
        summary: "Students explore particle vibration, transfer media, and why sound behaves differently across materials.",
        order: 1,
      },
      {
        id: "frequency-and-pitch",
        title: "Frequency and Pitch",
        description: "Relate wave frequency to the pitch heard in everyday sounds.",
        content: "This section includes comparison examples, listening prompts, and graph interpretation around pitch and loudness.",
        attachedFileIds: [],
        summary: "This section includes comparison examples, listening prompts, and graph interpretation around pitch and loudness.",
        order: 2,
      },
    ],
  },
  {
    id: "electricity-basics",
    title: "Electricity Basics",
    description: "Learn electric current, voltage, resistance, and simple circuit behavior.",
    status: "published",
    lessons: 3,
    duration: "1 week",
    order: 3,
    attachedFileIds: [],
    submodules: [
      {
        id: "current-and-voltage",
        title: "Current and Voltage",
        description: "Introduce electric charge flow and potential difference in circuits.",
        content: "A starter lesson on current and voltage using battery, wire, and bulb examples with simple circuit sketches.",
        attachedFileIds: [],
        summary: "A starter lesson on current and voltage using battery, wire, and bulb examples with simple circuit sketches.",
        order: 0,
      },
      {
        id: "resistance-and-ohms-law",
        title: "Resistance and Ohm's Law",
        description: "Use Ohm's law to link current, voltage, and resistance.",
        content: "Students practice formula substitution, interpret resistor behavior, and solve short circuit calculation tasks.",
        attachedFileIds: [],
        summary: "Students practice formula substitution, interpret resistor behavior, and solve short circuit calculation tasks.",
        order: 1,
      },
      {
        id: "series-and-parallel-circuits",
        title: "Series and Parallel Circuits",
        description: "Compare current flow and bulb behavior in common circuit arrangements.",
        content: "This submodule covers circuit diagrams, rule comparisons, and common troubleshooting examples in labs.",
        attachedFileIds: [],
        summary: "This submodule covers circuit diagrams, rule comparisons, and common troubleshooting examples in labs.",
        order: 2,
      },
    ],
  },
];
