// Provides the first half of seeded subject modules for physics.
import type { SubjectModuleItem } from "./subjectModulesTypes";

export const subjectModulesSeedPhysicsA: SubjectModuleItem[] = [
  {
    id: "forces-and-motion",
    title: "Forces and Motion",
    description: "Study speed, velocity, acceleration, and Newton's laws through simple motion examples.",
    status: "published",
    lessons: 3,
    duration: "1 week",
    order: 0,
    attachedFileIds: [],
    submodules: [
      {
        id: "speed-and-velocity",
        title: "Speed and Velocity",
        description: "Distinguish scalar and vector motion measurements using classroom examples.",
        content: "Students compare distance-time and displacement-time situations, then interpret motion scenarios from graphs and short experiments.",
        attachedFileIds: [],
        summary: "Students compare distance-time and displacement-time situations, then interpret motion scenarios from graphs and short experiments.",
        order: 0,
      },
      {
        id: "acceleration-in-daily-life",
        title: "Acceleration in Daily Life",
        description: "Connect acceleration to cars, bikes, and everyday changes in motion.",
        content: "Lesson notes and worked problems explain acceleration as a rate of change, with practical examples and graph reading tasks.",
        attachedFileIds: [],
        summary: "Lesson notes and worked problems explain acceleration as a rate of change, with practical examples and graph reading tasks.",
        order: 1,
      },
      {
        id: "newtons-laws-of-motion",
        title: "Newton's Laws of Motion",
        description: "Apply Newton's three laws to pushes, pulls, and balanced forces.",
        content: "A guided submodule with force diagrams, station questions, and short scenario analysis on inertia and net force.",
        attachedFileIds: [],
        summary: "A guided submodule with force diagrams, station questions, and short scenario analysis on inertia and net force.",
        order: 2,
      },
    ],
  },
  {
    id: "energy-and-work",
    title: "Energy and Work",
    description: "Explore work, power, kinetic energy, and potential energy in physical systems.",
    status: "published",
    lessons: 3,
    duration: "1 week",
    order: 1,
    attachedFileIds: [],
    submodules: [
      {
        id: "work-done-by-a-force",
        title: "Work Done by a Force",
        description: "Calculate work using force and displacement in simple systems.",
        content: "Students solve work problems, identify when no work is done, and examine force direction using guided diagrams.",
        attachedFileIds: [],
        summary: "Students solve work problems, identify when no work is done, and examine force direction using guided diagrams.",
        order: 0,
      },
      {
        id: "kinetic-and-potential-energy",
        title: "Kinetic and Potential Energy",
        description: "Compare stored and moving energy in ramps, springs, and falling objects.",
        content: "This submodule blends diagrams, formulas, and motion examples to show how energy changes form in a system.",
        attachedFileIds: [],
        summary: "This submodule blends diagrams, formulas, and motion examples to show how energy changes form in a system.",
        order: 1,
      },
      {
        id: "power-in-mechanical-systems",
        title: "Power in Mechanical Systems",
        description: "Measure how quickly work is done in machines and motion tasks.",
        content: "Teaching materials explain power, efficiency, and real-world machine examples with short application questions.",
        attachedFileIds: [],
        summary: "Teaching materials explain power, efficiency, and real-world machine examples with short application questions.",
        order: 2,
      },
    ],
  },
];
