/**
 * routes
 * ------
 * Defines shared route constants for the teacher dashboard.
 */
export const TEACHER_ROUTES = {
  ROOT: "/dashboard/teacher",
  ASSIGNMENTS: "/dashboard/teacher/assignments",
  ASSIGNMENTS_CREATE: "/dashboard/teacher/assignments/create",
  ASSIGNMENTS_UPLOAD: "/dashboard/teacher/assignments/upload",
  ASSIGNMENTS_PREVIEW: "/dashboard/teacher/assignments/:assignmentId/preview",
  ASSIGNMENTS_EDIT: "/dashboard/teacher/assignments/:assignmentId/edit",
  ASSIGNMENTS_REPUBLISH: "/dashboard/teacher/assignments/:assignmentId/republish",
  EXAMS: "/dashboard/teacher/exams",
  EXAMS_CREATE: "/dashboard/teacher/exams/create",
  EXAMS_PREVIEW: "/dashboard/teacher/exams/:examId/preview",
  EXAMS_EDIT: "/dashboard/teacher/exams/:examId/edit",
  EXAMS_REPUBLISH: "/dashboard/teacher/exams/:examId/republish",
  GRADES: "/dashboard/teacher/grades",
  GRADES_WORKSPACE: "/dashboard/teacher/grades/workspace",
  GRADES_WORKSPACE_ITEM: "/dashboard/teacher/grades/workspace/:itemId",
  GRADES_WORKSPACE_ITEM_SUBMITTED: "/dashboard/teacher/grades/workspace/:itemId/submitted",
  GRADES_WORKSPACE_ITEM_NOT_SUBMITTED: "/dashboard/teacher/grades/workspace/:itemId/not-submitted",
  GRADES_WORKSPACE_ITEM_SUBMISSION: "/dashboard/teacher/grades/workspace/:itemId/submissions/:submissionId",
  GRADES_CREATE: "/dashboard/teacher/grades/create",
  GRADES_EXPORT: "/dashboard/teacher/grades/export",
  GRADES_SUBMISSIONS: "/dashboard/teacher/grades/submissions",
  GRADES_SUBMISSION_DETAILS: "/dashboard/teacher/grades/submissions/:submissionId",
  QUESTIONS_BUILDER_CREATE: "/dashboard/teacher/questions/create",
  QUESTIONS_BUILDER_EDIT: "/dashboard/teacher/questions/edit/:itemId",
  ATTENDANCE: "/dashboard/teacher/attendance",
  ATTENDANCE_CREATE: "/dashboard/teacher/attendance/create",
  ATTENDANCE_SESSION: "/dashboard/teacher/attendance/sessions/:sessionId",
  ATTENDANCE_SESSION_EDIT: "/dashboard/teacher/attendance/sessions/:sessionId/edit",
  ATTENDANCE_EDIT: "/dashboard/teacher/attendance/:attendanceId/edit",
  ANNOUNCEMENTS: "/dashboard/teacher/announcements",
  ANNOUNCEMENTS_CREATE: "/dashboard/teacher/announcements/create",
  ANNOUNCEMENTS_EDIT: "/dashboard/teacher/announcements/edit/:announcementId",
  MESSAGES: "/dashboard/teacher/messages",
  MESSAGE_DETAILS: "/dashboard/teacher/messages/:messageId",
} as const;
