import { Subject, SubjectStatus } from './types';

// Generate random date within last 180 days
const getRandomDate = () => {
  const now = new Date();
  const daysAgo = Math.floor(Math.random() * 180);
  const randomDate = new Date(now.getTime() - (daysAgo * 24 * 60 * 60 * 1000));
  return randomDate.toISOString();
};

// Generate random mock metrics
const getRandomStudentCount = () => Math.floor(Math.random() * 40) + 15; // 15-55 students
const getRandomPassingRate = () => Math.floor(Math.random() * 40) + 60; // 60-100% passing rate

// Rwandan teacher names
const teachers = [
  "Mr. Jean Baptiste Uwimana",
  "Ms. Marie Claire Mukamana", 
  "Mr. Paul Nkubana",
  "Ms. Agnes Nyirahabimana",
  "Mr. Emmanuel Bizimana",
  "Ms. Claudine Uwizeyimana",
  "Mr. David Habimana",
  "Ms. Grace Mukandayisenga",
  "Mr. Eric Ndayisaba",
  "Ms. Josephine Mukarugwiza"
];

// Available class options
const classOptions = [
  "P1 A", "P1 B", "P2 A", "P2 B", "P3 A", "P3 B", 
  "P4 A", "P4 B", "P5 A", "P5 B", "P6 A", "P6 B",
  "S1 A", "S1 B", "S2 A", "S2 B", "S3 A", "S3 B",
  "S4 A", "S4 B", "S5 A", "S5 B", "S6 A", "S6 B"
];

// Generate random classes assignment
const getRandomClasses = () => {
  const numClasses = Math.floor(Math.random() * 4) + 1; // 1-4 classes
  const shuffled = [...classOptions].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, numClasses);
};

// Realistic Rwandan curriculum subjects
export const SUBJECTS: Subject[] = [
  // Core subjects
  {
    id: "subj-001",
    name: "Kinyarwanda",
    code: "KIN-001",
    classes: getRandomClasses(),
    teacherName: teachers[0],
    numberOfStudents: getRandomStudentCount(),
    passingRate: getRandomPassingRate(),
    status: "Active",
    updatedAt: getRandomDate()
  },
  {
    id: "subj-002",
    name: "English",
    code: "ENG-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "English language skills development",
    category: "LANGUAGES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-003",
    name: "Mathematics",
    code: "MATH-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Basic mathematical concepts and problem solving",
    category: "MATHEMATICS",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-004",
    name: "Science",
    code: "SCI-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Elementary science concepts",
    category: "SCIENCES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-005",
    name: "Social Studies",
    code: "SS-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Basic understanding of society and environment",
    category: "SOCIAL_STUDIES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-006",
    name: "Creative Arts",
    code: "ART-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Drawing, painting, and creative expression",
    category: "ARTS",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-007",
    name: "Physical Education",
    code: "PE-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Physical fitness and sports activities",
    category: "PHYSICAL_EDUCATION",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-008",
    name: "French",
    code: "FR-P1",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Basic French language skills",
    category: "LANGUAGES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },

  // LOWER SECONDARY SUBJECTS
  {
    id: "subj-009",
    name: "Kinyarwanda",
    code: "KIN-LS1",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Advanced Kinyarwanda language and literature",
    category: "LANGUAGES",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-010",
    name: "English",
    code: "ENG-LS1",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "English language and literature",
    category: "LANGUAGES",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-011",
    name: "French",
    code: "FR-LS1",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "French language and communication",
    category: "LANGUAGES",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-012",
    name: "Mathematics",
    code: "MATH-LS1",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Algebra, geometry, and mathematical reasoning",
    category: "MATHEMATICS",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-013",
    name: "Physics",
    code: "PHY-LS1",
    level: "Lower Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Basic physics principles and experiments",
    category: "SCIENCES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-014",
    name: "Chemistry",
    code: "CHEM-LS1",
    level: "Lower Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Introduction to chemical concepts",
    category: "SCIENCES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-015",
    name: "Biology",
    code: "BIO-LS1",
    level: "Lower Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Life sciences and biological processes",
    category: "SCIENCES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-016",
    name: "History",
    code: "HIST-LS1",
    level: "Lower Secondary",
    streams: ["Arts", "General"],
    status: "Active",
    description: "Rwandan and world history",
    category: "SOCIAL_STUDIES",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-017",
    name: "Geography",
    code: "GEO-LS1",
    level: "Lower Secondary",
    streams: ["Arts", "General"],
    status: "Active",
    description: "Physical and human geography",
    category: "SOCIAL_STUDIES",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-018",
    name: "Entrepreneurship",
    code: "ENT-LS1",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Basic business and entrepreneurship skills",
    category: "LIFE_SKILLS",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-019",
    name: "Computer Studies",
    code: "ICT-LS1",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Basic computer literacy and programming",
    category: "TECHNOLOGY",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-020",
    name: "Music",
    code: "MUS-LS1",
    level: "Lower Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Music theory and practical skills",
    category: "ARTS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },

  // UPPER SECONDARY SUBJECTS
  {
    id: "subj-021",
    name: "Advanced Mathematics",
    code: "AMATH-US1",
    level: "Upper Secondary",
    streams: ["Science", "Technical"],
    status: "Active",
    description: "Calculus, statistics, and advanced algebra",
    category: "MATHEMATICS",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-022",
    name: "Pure Mathematics",
    code: "PMATH-US1",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Pure mathematical concepts and proofs",
    category: "MATHEMATICS",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-023",
    name: "Physics",
    code: "PHY-US1",
    level: "Upper Secondary",
    streams: ["Science", "Technical"],
    status: "Active",
    description: "Advanced physics and laboratory work",
    category: "SCIENCES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-024",
    name: "Chemistry",
    code: "CHEM-US1",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Organic and inorganic chemistry",
    category: "SCIENCES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-025",
    name: "Biology",
    code: "BIO-US1",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Advanced biology and genetics",
    category: "SCIENCES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-026",
    name: "Economics",
    code: "ECON-US1",
    level: "Upper Secondary",
    streams: ["Arts", "Commerce"],
    status: "Active",
    description: "Microeconomics and macroeconomics",
    category: "SOCIAL_STUDIES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-027",
    name: "Entrepreneurship",
    code: "ENT-US1",
    level: "Upper Secondary",
    streams: ["Commerce", "General"],
    status: "Active",
    description: "Advanced business planning and management",
    category: "LIFE_SKILLS",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-028",
    name: "Literature in English",
    code: "LIT-US1",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "English literature analysis and criticism",
    category: "LANGUAGES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-029",
    name: "History",
    code: "HIST-US1",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Advanced historical studies",
    category: "SOCIAL_STUDIES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-030",
    name: "Geography",
    code: "GEO-US1",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Advanced geography and cartography",
    category: "SOCIAL_STUDIES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-031",
    name: "Computer Science",
    code: "CS-US1",
    level: "Upper Secondary",
    streams: ["Science", "Technical"],
    status: "Active",
    description: "Programming and computer systems",
    category: "TECHNOLOGY",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-032",
    name: "Fine Arts",
    code: "FA-US1",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Advanced visual arts and design",
    category: "ARTS",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },

  // Additional subjects across all levels
  {
    id: "subj-033",
    name: "Agriculture",
    code: "AGR-P2",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Basic farming and gardening skills",
    category: "LIFE_SKILLS",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-034",
    name: "Swahili",
    code: "SW-LS2",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "East African lingua franca",
    category: "LANGUAGES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-035",
    name: "Technical Drawing",
    code: "TD-US2",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Engineering and architectural drawing",
    category: "TECHNOLOGY",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-036",
    name: "Accounting",
    code: "ACC-US2",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Financial accounting principles",
    category: "SOCIAL_STUDIES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-037",
    name: "Environmental Science",
    code: "ENV-LS3",
    level: "Lower Secondary",
    streams: ["Science", "General"],
    status: "Active",
    description: "Environmental conservation and sustainability",
    category: "SCIENCES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-038",
    name: "Civic Education",
    code: "CIV-LS4",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Citizenship and civic responsibility",
    category: "SOCIAL_STUDIES",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-039",
    name: "Religious Studies",
    code: "REL-P3",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Moral and religious education",
    category: "LIFE_SKILLS",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-040",
    name: "Drama",
    code: "DRA-LS5",
    level: "Lower Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Theatre arts and performance",
    category: "ARTS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },

  // ARCHIVED SUBJECTS (handful as requested)
  {
    id: "subj-041",
    name: "Latin",
    code: "LAT-US3",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Archived",
    description: "Classical Latin language",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-042",
    name: "Woodworking",
    code: "WW-LS6",
    level: "Lower Secondary",
    streams: ["Technical"],
    status: "Archived",
    description: "Traditional woodworking crafts",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-043",
    name: "Typewriting",
    code: "TW-US4",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Archived",
    description: "Manual typewriting skills",
    category: "TECHNOLOGY",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-044",
    name: "Traditional Dance",
    code: "TD-P4",
    level: "Primary",
    streams: ["Arts"],
    status: "Archived",
    description: "Rwandan traditional dance forms",
    category: "ARTS",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-045",
    name: "Home Economics",
    code: "HE-LS7",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Archived",
    description: "Household management and cooking",
    category: "LIFE_SKILLS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },

  // More active subjects to reach 120+
  {
    id: "subj-046",
    name: "Spanish",
    code: "SP-US5",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Spanish language and culture",
    category: "LANGUAGES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-047",
    name: "German",
    code: "GER-US6",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "German language studies",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-048",
    name: "Chinese",
    code: "CHI-US7",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Mandarin Chinese language",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-049",
    name: "Philosophy",
    code: "PHIL-US8",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Introduction to philosophical thinking",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-050",
    name: "Psychology",
    code: "PSY-US9",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Basic psychological concepts",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-051",
    name: "Sociology",
    code: "SOC-US10",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Study of society and social behavior",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-052",
    name: "Statistics",
    code: "STAT-US11",
    level: "Upper Secondary",
    streams: ["Science", "Commerce"],
    status: "Active",
    description: "Statistical analysis and data interpretation",
    category: "MATHEMATICS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-053",
    name: "Geology",
    code: "GEL-US12",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Earth sciences and mineral studies",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-054",
    name: "Astronomy",
    code: "AST-US13",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Study of celestial objects and space",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-055",
    name: "Robotics",
    code: "ROB-US14",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Introduction to robotics and automation",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-056",
    name: "Web Design",
    code: "WEB-US15",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "HTML, CSS, and web development",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-057",
    name: "Digital Arts",
    code: "DA-US16",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Digital graphic design and multimedia",
    category: "ARTS",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-058",
    name: "Photography",
    code: "PHOTO-US17",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Digital photography and editing",
    category: "ARTS",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-059",
    name: "Film Studies",
    code: "FILM-US18",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Cinema history and film production",
    category: "ARTS",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-060",
    name: "Journalism",
    code: "JOUR-US19",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "News writing and media studies",
    category: "LANGUAGES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },

  // Continue with more subjects to reach 120+...
  // Adding variations for different streams and year groups

  {
    id: "subj-061",
    name: "Kinyarwanda Literature",
    code: "KINLIT-US20",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Advanced Kinyarwanda literary analysis",
    category: "LANGUAGES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-062",
    name: "French Literature",
    code: "FRLIT-US21",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "French literary works and criticism",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-063",
    name: "Business Studies",
    code: "BUS-US22",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Business management and operations",
    category: "SOCIAL_STUDIES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-064",
    name: "Marketing",
    code: "MKT-US23",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Marketing principles and strategies",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-065",
    name: "Finance",
    code: "FIN-US24",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Financial management and banking",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-066",
    name: "Engineering Drawing",
    code: "ED-US25",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Technical and engineering drawing skills",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-067",
    name: "Electronics",
    code: "ELEC-US26",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Electronic circuits and components",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-068",
    name: "Mechanics",
    code: "MECH-US27",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Mechanical systems and repair",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-069",
    name: "Architecture",
    code: "ARCH-US28",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Architectural design principles",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-070",
    name: "Nutrition",
    code: "NUT-LS8",
    level: "Lower Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Food science and nutrition",
    category: "SCIENCES",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-071",
    name: "Health Education",
    code: "HEAL-LS9",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Personal health and hygiene",
    category: "LIFE_SKILLS",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-072",
    name: "First Aid",
    code: "FA-LS10",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Basic first aid and emergency response",
    category: "LIFE_SKILLS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-073",
    name: "Leadership Skills",
    code: "LEAD-US29",
    level: "Upper Secondary",
    streams: ["General"],
    status: "Active",
    description: "Leadership and team management",
    category: "LIFE_SKILLS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-074",
    name: "Public Speaking",
    code: "PS-US30",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Communication and presentation skills",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-075",
    name: "Debate",
    code: "DEB-US31",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Argumentative skills and critical thinking",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },

  // Adding more Primary level subjects
  {
    id: "subj-076",
    name: "Reading",
    code: "READ-P5",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Reading comprehension and fluency",
    category: "LANGUAGES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-077",
    name: "Writing",
    code: "WRIT-P6",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Creative and academic writing skills",
    category: "LANGUAGES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-078",
    name: "Basic Computing",
    code: "COMP-P7",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Introduction to computers",
    category: "TECHNOLOGY",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-079",
    name: "Nature Studies",
    code: "NAT-P8",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Plants, animals, and environment",
    category: "SCIENCES",
    maxCapacity: 35,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-080",
    name: "Community Service",
    code: "CS-P9",
    level: "Primary",
    streams: ["General"],
    status: "Active",
    description: "Community involvement and service",
    category: "LIFE_SKILLS",
    maxCapacity: 40,
    updatedAt: getRandomDate()
  },

  // More Lower Secondary subjects
  {
    id: "subj-081",
    name: "Research Methods",
    code: "RM-LS11",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Basic research and study skills",
    category: "LIFE_SKILLS",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-082",
    name: "Critical Thinking",
    code: "CT-LS12",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Logical reasoning and analysis",
    category: "LIFE_SKILLS",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-083",
    name: "Creative Writing",
    code: "CW-LS13",
    level: "Lower Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Fiction and poetry writing",
    category: "LANGUAGES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-084",
    name: "Digital Literacy",
    code: "DL-LS14",
    level: "Lower Secondary",
    streams: ["General"],
    status: "Active",
    description: "Digital citizenship and online safety",
    category: "TECHNOLOGY",
    maxCapacity: 30,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-085",
    name: "Data Analysis",
    code: "DA-LS15",
    level: "Lower Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Basic statistical analysis",
    category: "MATHEMATICS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },

  // More Upper Secondary subjects
  {
    id: "subj-086",
    name: "Applied Mathematics",
    code: "APMATH-US32",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Mathematics for engineering applications",
    category: "MATHEMATICS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-087",
    name: "Discrete Mathematics",
    code: "DMATH-US33",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Logic, sets, and combinatorics",
    category: "MATHEMATICS",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-088",
    name: "Biochemistry",
    code: "BIOCHEM-US34",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Chemical processes in living organisms",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-089",
    name: "Microbiology",
    code: "MICRO-US35",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Study of microorganisms",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-090",
    name: "Environmental Chemistry",
    code: "ECHEM-US36",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Chemical processes in the environment",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-091",
    name: "Astrophysics",
    code: "ASTRO-US37",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Physics of celestial objects",
    category: "SCIENCES",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-092",
    name: "Molecular Biology",
    code: "MOLBIO-US38",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Molecular mechanisms of biological processes",
    category: "SCIENCES",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-093",
    name: "Organic Chemistry",
    code: "OCHEM-US39",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Chemistry of carbon compounds",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-094",
    name: "Inorganic Chemistry",
    code: "ICHEM-US40",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Chemistry of non-carbon elements",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-095",
    name: "Physical Chemistry",
    code: "PCHEM-US41",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Chemical phenomena through physics",
    category: "SCIENCES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-096",
    name: "Calculus",
    code: "CALC-US42",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Differential and integral calculus",
    category: "MATHEMATICS",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-097",
    name: "Linear Algebra",
    code: "LINALG-US43",
    level: "Upper Secondary",
    streams: ["Science"],
    status: "Active",
    description: "Vector spaces and linear transformations",
    category: "MATHEMATICS",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-098",
    name: "Probability",
    code: "PROB-US44",
    level: "Upper Secondary",
    streams: ["Science", "Commerce"],
    status: "Active",
    description: "Probability theory and applications",
    category: "MATHEMATICS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-099",
    name: "Game Theory",
    code: "GAME-US45",
    level: "Upper Secondary",
    streams: ["Science", "Commerce"],
    status: "Active",
    description: "Mathematical study of strategic decisions",
    category: "MATHEMATICS",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-100",
    name: "Operations Research",
    code: "OR-US46",
    level: "Upper Secondary",
    streams: ["Science", "Commerce"],
    status: "Active",
    description: "Mathematical optimization techniques",
    category: "MATHEMATICS",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },

  // Final subjects to reach 120+
  {
    id: "subj-101",
    name: "International Relations",
    code: "IR-US47",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Global politics and diplomacy",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-102",
    name: "Political Science",
    code: "POLI-US48",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Government systems and political theory",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-103",
    name: "Anthropology",
    code: "ANTH-US49",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Study of human cultures and societies",
    category: "SOCIAL_STUDIES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-104",
    name: "Linguistics",
    code: "LING-US50",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Scientific study of language",
    category: "LANGUAGES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-105",
    name: "Translation Studies",
    code: "TRANS-US51",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Theory and practice of translation",
    category: "LANGUAGES",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-106",
    name: "Media Studies",
    code: "MEDIA-US52",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Mass media and communication",
    category: "LANGUAGES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-107",
    name: "Cultural Studies",
    code: "CULT-US53",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Cultural practices and representations",
    category: "SOCIAL_STUDIES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-108",
    name: "Gender Studies",
    code: "GEND-US54",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Gender roles and identity",
    category: "SOCIAL_STUDIES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-109",
    name: "Peace Studies",
    code: "PEACE-US55",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Conflict resolution and peacebuilding",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-110",
    name: "Human Rights",
    code: "HR-US56",
    level: "Upper Secondary",
    streams: ["Arts"],
    status: "Active",
    description: "Human rights law and advocacy",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-111",
    name: "Development Studies",
    code: "DEV-US57",
    level: "Upper Secondary",
    streams: ["Arts", "Commerce"],
    status: "Active",
    description: "Economic and social development",
    category: "SOCIAL_STUDIES",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-112",
    name: "Project Management",
    code: "PM-US58",
    level: "Upper Secondary",
    streams: ["Commerce", "Technical"],
    status: "Active",
    description: "Planning and managing projects",
    category: "LIFE_SKILLS",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-113",
    name: "Quality Management",
    code: "QM-US59",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Quality control and assurance",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-114",
    name: "Supply Chain Management",
    code: "SCM-US60",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Logistics and supply chain optimization",
    category: "SOCIAL_STUDIES",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-115",
    name: "Digital Marketing",
    code: "DM-US61",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Online marketing strategies",
    category: "TECHNOLOGY",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-116",
    name: "E-commerce",
    code: "ECOM-US62",
    level: "Upper Secondary",
    streams: ["Commerce"],
    status: "Active",
    description: "Online business and trade",
    category: "TECHNOLOGY",
    maxCapacity: 25,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-117",
    name: "Cybersecurity",
    code: "CYBER-US63",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Information security and protection",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-118",
    name: "Data Science",
    code: "DS-US64",
    level: "Upper Secondary",
    streams: ["Science", "Technical"],
    status: "Active",
    description: "Big data analysis and machine learning",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-119",
    name: "Artificial Intelligence",
    code: "AI-US65",
    level: "Upper Secondary",
    streams: ["Science", "Technical"],
    status: "Active",
    description: "AI concepts and applications",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-120",
    name: "Machine Learning",
    code: "ML-US66",
    level: "Upper Secondary",
    streams: ["Science", "Technical"],
    status: "Active",
    description: "Algorithms that learn from data",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-121",
    name: "Blockchain Technology",
    code: "BLOCK-US67",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Distributed ledger technology",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-122",
    name: "Internet of Things",
    code: "IOT-US68",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Connected devices and smart systems",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-123",
    name: "Cloud Computing",
    code: "CLOUD-US69",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Cloud infrastructure and services",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-124",
    name: "Mobile App Development",
    code: "MOBILE-US70",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Creating applications for mobile devices",
    category: "TECHNOLOGY",
    maxCapacity: 20,
    updatedAt: getRandomDate()
  },
  {
    id: "subj-125",
    name: "Game Development",
    code: "GAMEDEV-US71",
    level: "Upper Secondary",
    streams: ["Technical"],
    status: "Active",
    description: "Video game design and programming",
    category: "TECHNOLOGY",
    maxCapacity: 15,
    updatedAt: getRandomDate()
  }
];